name: Release

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    release:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: ${{ github.event.repository.name }}
                      exe_extension: ""
                    - os: macos-latest
                      artifact_name: ${{ github.event.repository.name }}
                      exe_extension: ""
                    - os: windows-latest
                      artifact_name: ${{ github.event.repository.name }}
                      exe_extension: ".exe"
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Cargo Registry
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  target/release
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

            - name: Build
              run: cargo build --release

            - name: Asset name
              id: asset_name
              run: |
                  echo "HOST_TRIPLE=$(rustc -vV | awk '/^host/ { print $2 }')" >> $GITHUB_OUTPUT

            - name: Rename binary for Windows
              if: matrix.os == 'windows-latest'
              run: |
                  mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.artifact_name }}${{ matrix.exe_extension }}

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/release/${{ matrix.artifact_name }}${{ matrix.exe_extension }}
                  asset_name: ${{ github.event.repository.name }}-${{ steps.asset_name.outputs.HOST_TRIPLE }}${{ matrix.exe_extension }}
                  tag: ${{ github.ref }}
